baseURL = '/'
languageCode = 'cs-cz'
title = 'Červený notes - last'
theme = 'ananke'
canonifyURLs = true
DefaultContentLanguage = 'cs'
SectionPagesMenu = 'main'
Paginate = 13
summaryLength = 20
[languages]
  [languages.cs]
    title = 'Červený notes - L'
    weight = 1
    contentDir = "content/cs"
  [languages.en]
    title = "red book"
    weight = 2
    contentDir = "content/en"
